config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # rails admin mounting
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'bookings/index'
 
  resources :recipies
  resources :chefs, except: :index
  resources :listings
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: 'listings#home'

  # allows bookings to have reviews
  resources :bookings do
    resources :reviews
  end
  # allows recipes to have comments
  resources :recipes do
    resources :comments
  end
  resources :payments, only: [:create]  # stripe config
  get'/payments/success', to:'payments#success'
  get'/payments/cancel',to:'payments#cancel'
  post "/payments/webhook", to: "payments#webhook"
end

app/models/listing.rb
# frozen_string_literal: true

class Listing < ApplicationRecord
  belongs_to :chef # FK
  belongs_to :category # FK

  has_one :booking, dependent: :destroy
  has_one :user, through: :bookings
  
  validates :location, length: { in: 1..20 }
  validates :date_available, future: true #future validation check, disable to test locally
  validates :title, :description, :price, :category, presence: true
  validates :price, numericality: { only_integer: true, greater_than: -1, less_than: 4000 }
  validates :description, length: { in: 15..150 }
  validates :title, length: { in: 5..45 }
end

app/controllers/listings_controller.rb
# frozen_string_literal: true

class ListingsController < ApplicationController
  before_action :set_listing, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: :home
  before_action :authorize_chef, only: %i[new create]
  # GET /listings
  def index
    @listings = Listing.all.includes(%i[category chef])
  end

  # GET /listings/1
  def show
    @recipes = @listing.chef.recipes.all.includes([image_attachment: :blob]) # shows the chef who owns this listings reviews and recipes
    @reviews = @listing.chef.reviews.all.includes([:user])
  end

  def home #displays the total listings made on the site
    @listings = Listing.all.length
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit; end

  # POST /listings
  def create
    @listing = Listing.create(listing_params)
    @listing.chef = current_user.chef
    ListingMailer.send_new_listing_email(current_user).deliver #email service on new listing

    if @listing.save
      redirect_to @listing, notice: 'Listing was successfully created.'
    else
      render :new
    end
  end

  def get_categories
    @categories = Category.all
  end

  # PATCH/PUT /listings/1
  def update
    if @listing.update(listing_params)
      redirect_to @listing, notice: 'Listing was successfully updated.'
    else
      render :edit
    end
  end

  def bookings
    @bookings = current_user.bookings.all
  end

  # DELETE /listings/1
  def destroy
    @listing.destroy
    redirect_to listings_url, notice: 'Listing was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_listing
    @listing = Listing.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def listing_params
    params.require(:listing).permit(:title, :description, :location, :category_id, :price, :chef_id, :date_available)
  end
end

app/views/listings/_form.html.erb
<%= simple_form_for(@listing) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
        
    <%= f.input :date_available, required: true , input_html: { class: "form-control center" } %>
    <%= f.input :price, required: true , input_html: { class: "form-control center", max:4000, min:0 } %>
    <%= f.input :title, required: true , input_html: { class: "form-control center" } %>
    <%= f.input :description, required: true , input_html: { class: "form-control center" } %>
    
    <%= f.association :category, required: true , prompt: "Select Category", input_html: { class: "form-control center" }%>


    <%= f.input :location, required: true  , input_html: { class: "form-control center" }%>
    
    
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/home.html.erb
  <div class="card allign-self-center justify-content-center">
  <%= image_tag('melbourne.jpg', class:'card-img-top') %>
    <h1 class='card-title'>Welcome to ChefSwap</h1>
    <div class="card-body">
      <p class= "card-text lead">Connecting private chefs with amazing clients</p>
      <h2 class ="card-text lead">we currently have <%= @listings %> listings, care to add yours to the list?</h2>
      <%= link_to 'Listings', listings_path, class: 'btn btn-primary d-block' %>
    </div>
  </div>

app/views/listings/index.html.erb
 
  <%= flash[:notice] %>
  <% if current_user.is_chef? %>
    <%= link_to 'New Listing', new_listing_path,class:'btn btn-dark d-block pb-3' %>
  <% end %>


<h1 class='text-center card-title'>Chef listings</h1>
<div class="d-flex justify-content-center bg-light">


<% @listings.each do |listing| %>
  <div class="card mt-3" style="width: 25rem;">
    <div class="card-body">
    <h5 class="card-title"><%= listing.title %></h5>
    <h5 class="card-text lead">On: <%= listing.date_available %></h5>

    <h6 class="card-subtitle mb-2 text-muted"><%=listing.category.name%></h6>
    <h5 class="card-title text-dark mb-1 align-self-center"> 
      <%= listing.chef.user.name %> 
    </h5>
    <h3>
      $<%= listing.price %>
    </h3>
      <p class="card-text lead"><%= listing.description %></p>
    <div class="text-right">
      <%= link_to "Show", listing_path(listing.id), class: "btn btn-primary" %>
    <% if user_signed_in? && current_user.is_chef? && current_user.chef.listings.include?(listing) %>
      <%= link_to "Delete", listing_path(listing.id), class: "btn btn-danger", method: :delete %>
      <%= link_to "Edit", edit_listing_path(listing), class: "btn btn-info"%>
    <% end %>
    </div>
  </div>
</div>

<% end %>

     

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="d-flex justify-content-center">
    <div class="card mb-3" style="width: 40vw;">
      <%= image_tag(@listing.chef.avatar, class:'card-img-top') %>
        <div class="card-body">
          <h5 class="card-title"><%= @listing.title %></h5>
          <p class="card-text lead"><%=@listing.chef.user.name %> is cooking <%=@listing.category.name %> style food on <%=@listing.date_available  %></p>
          <p class="card-text lead"><%= @listing.chef.bio %></p>
          <p class="card-text lead">$<%= @listing.price %></p>
          <p class="card-text lead"><%= @listing.description %></p>
          <p class="card-text lead"> in <%= @listing.location %></p>
        </div>
        <div class="card-body text-right">
        
        <% unless @listing.booked? || @listing.date_available.past? ||current_user.is_chef%>
          <button class= 'btn btn-success'id="stripe">Book!</button>
          <% else %>
          <button type="button" class="btn btn-primary  disabled"> Unavailable</button>
          <% end %>
          <%= javascript_pack_tag 'stripe' %>
        <% if current_user.is_chef && current_user.chef.listings.include?(@listing) %>
          <%= link_to 'Edit', edit_listing_path(@listing),class:'btn btn-warning' %> 
        <% end %>
          <%= link_to 'Back', listings_path,class: "btn btn-info" %>
    </div>
  </div>
</div>
</div>

<% unless @reviews.empty? %>
  <div class="card py-2"><%@reviews.each do |review| %>
    <h3 class="card-title"><%=review.user.name %>  Said that this chef was:  <%= review.rating ? "#{'Good!'}" : "#{'Bad!'}" %></h3>
    <p class="card-text lead"><%= review.content %></p>
    <% end %>
    <hr>
  </div>
<% end %>



  
<% unless @recipes.empty? %>

<div class=" d-flex flex-wrap">
  
      <% @recipes.each do |rec| %>
      
        <div class="card m-3" style="width: 18rem;">
          <%= image_tag(rec.image, class:'card-img-top') if rec.image.attached? %>
          <h5 class="card-title">  <%= rec.title %></h5>
        <p class="card-text lead"> <%= rec.body %></p>
        <%= link_to 'show', rec ,class:'btn btn-primary'%>
      </div>
        <% end %>
    </div>
</div>


<% end %>