config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # rails admin mounting
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'bookings/index'
 
  resources :recipies
  resources :chefs, except: :index
  resources :listings
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: 'listings#home'

  # allows bookings to have reviews
  resources :bookings do
    resources :reviews
  end
  # allows recipes to have comments
  resources :recipes do
    resources :comments
  end
  resources :payments, only: [:create]  # stripe config
  get'/payments/success', to:'payments#success'
  get'/payments/cancel',to:'payments#cancel'
  post "/payments/webhook", to: "payments#webhook"
end

app/models/chef.rb
class Chef < ApplicationRecord
  belongs_to :user # FK
  has_one_attached :avatar

  has_many :recipes, dependent: :destroy
  has_many :bookings
  has_many :listings, dependent: :destroy
  has_many :reviews, through: :bookings
  validates :avatar, presence: true
  validates :bio, presence: true, length: { in: 6..150 }
  validates :user_id, uniqueness: true # a user cant sign up as more than one chef
  validates :avatar, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5.megabytes } # file validation from  activestorage-validator gem
end

app/controllers/chefs_controller.rb
# frozen_string_literal: true

class ChefsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_chef, only: %i[show edit update destroy]
  before_action :owner_chef?, only: %i[edit update destroy]
  before_action :authenticate_chef!
  skip_before_action :check_chef_attributes, only: %i[new create]
  # GET /chefs/new
  def new
    @chef = Chef.new
  end

  # POST /chefs
  def create
    @chef = Chef.new(chef_params)
    @chef.user = current_user

    if @chef.save
      redirect_to @chef, notice: 'Chef was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /chefs/1
  def update
    if @chef.update(chef_params)
      redirect_to @chef, notice: 'Chef was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /chefs/1
  def destroy
    @chef.destroy
    redirect_to chefs_url, notice: 'Chef was successfully destroyed.'
  end

  private
 #determines if the chef that is signde in is the owner of the item
  def owner_chef?
    Chef.find_by(user_id: current_user.id).id
  end
 ## determines if the current use is a chef to show them chef only pages
  def authenticate_chef!
    redirect_to listings_path, notice: 'you must be a chef to access this.' unless current_user.is_chef?
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_chef
    @chef = Chef.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def chef_params
    params.require(:chef).permit(:bio, :id, :avatar)
  end
end

app/helpers/chef_helper.rb
module ChefHelper
end

app/views/chefs/_form.html.erb
<div class="col-7">
  <%= simple_form_for(@chef) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <h2 class="text-center">Tell us about yourself</h2>
    <div class="form-inputs">
      <div class="form-group">
        <%= f.input :avatar, required: true,input_html: { accept: 'image/png, image/jpg, image/jpeg', class: 'form-control' }, hint: "Got a better picture?"%>
      </div>
      <div class="form-grop">
        <%= f.input :bio , required: true ,input_html: { class: 'form-control pb-6' }, placeholder: "If people wanted food from a stranger they'd go to mcdonalds, put yourself out there." %>
      </div>
    </div>

    <div class="form-actions pt-3 text-right">
      <%= f.button :submit,class:'btn btn-primary block' %>
    </div>
  <% end %>
</div>

app/views/chefs/edit.html.erb
<h1>Editing your bio</h1>

<%= render 'form', chef: @chef %>

<%= link_to 'Back', listings_path, class:'btn btn-dark'%>

app/views/chefs/new.html.erb
<div class="container">
<div class="d-flex align-items-center justify-content-center">

<%= render 'form', chef: @chef %>
</div>
</div>

app/views/chefs/show.html.erb
<p id="notice"><%= notice %></p>


 <div class="container ">
  <h1 class="text-center">This is how people will see you in the listings.</h1>
  <div class="card text-center d-flex  " style="width: 50vw;">
  
    <%= image_tag(@chef.avatar, class:'card-img-top') %>
    <h5 class="card-title"> <strong>Name:</strong> <%= @chef.user.name %></h5>
   <p class="card-text">  <%= @chef.bio %></p>
   <%= link_to 'listings', listings_path ,class:'btn btn-primary d-block'%>
  
  <h3>Not quite right? change the bio and profile picture <%= link_to 'Here', edit_chef_path(@chef) %></h3>
 
 
  </div>
 </div>