config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # rails admin mounting
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'bookings/index'
 
  resources :recipies
  resources :chefs, except: :index
  resources :listings
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: 'listings#home'

  # allows bookings to have reviews
  resources :bookings do
    resources :reviews
  end
  # allows recipes to have comments
  resources :recipes do
    resources :comments
  end
  resources :payments, only: [:create]  # stripe config
  get'/payments/success', to:'payments#success'
  get'/payments/cancel',to:'payments#cancel'
  post "/payments/webhook", to: "payments#webhook"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :chef # FK

  has_many :comments, dependent: :destroy
  has_rich_text :body
  has_one_attached :image

  validates :title, :body, :image, :cooktime, presence: true
  validates :body, length: { in: 15..1000 }
  validates :title, length: { in: 5..45 }
  validates :cooktime, numericality: { only_integer: true, greater_than: -1, less_than: 400 }
  validates :image, presence: true, blob: { content_type: ['image/png', 'image/jpg', 'image/jpeg'], size_range: 1..5.megabytes } # gem validator activestorage-validator
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  before_action :authenticate_user!
  before_action :authorize_chef, except: :show
  def index
    @recipes = current_user.chef.recipes.all.includes([image_attachment: :blob]) # shows the current chef their recipes and allows them to edit or delete their recipes
  end

  def show; end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.create(recipe_params)
  
   @recipe.chef = current_user.chef 
   if @recipe.save
      redirect_to @recipe, notice: 'recipe was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /recipes/1
  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: 'recipe was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /recipes/1
  def destroy
    @recipe.destroy
    redirect_to recipes_url, notice: 'recipe was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:title, :cooktime, :body, :image)
  end
end

app/views/recipes/_comments.html.erb
<div class="mb-5">
  <h4 class="my-4 p-5 ">Recipe comments</h4>
  <hr>

  
   <p>  There are  <%= @recipe.comments.count %> comments on this Recipe.</p>
  <%= render @recipe.comments %>

  <hr>
  <p class="lead">leave a comment:</p>
  <%= render 'comments/form' %>
</div>

app/views/recipes/_form.html.erb
<%= simple_form_for(@recipe) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title, required: true ,input_html: { class: 'form-control' }, placeholder: "Got a fancy name with at least 5 chars?" %>
    <%= f.input :cooktime , label: ' Time to cook in minutes',required: true ,input_html: { class: 'form-control' },hint:' give us a rough numberhere. '%>
    <%= f.input :image, required: true ,input_html: { accept: 'image/png, image/jpg, image/jpeg', class: 'form-control' },hint:'People eat with their eyes, give them a feast.' %>
    <%= f.input :body, label: 'Method',  as: :rich_text_area,required: true ,input_html: { class: 'form-control' }, placeholder: "There has to be SOME method to the madness!",hint:' 15 char minimum ' %>
    
    
  </div>

  <div class="form-actions">
    <%= f.button :submit ,class:'btn btn-primary'%>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>


  <h1 class='text-center'>Your Recipes</h1>
<%= link_to 'New recipe', new_recipe_path, class:'btn btn-dark d-block pb-3 mb-4' %>
<div class="container d-flex justify-content-center pt-4">
  <div class="card pb-4 " style="width: 25rem;">
    <% @recipes.each do |rec| %>

  <%= image_tag(rec.image, class:'card-img-top') if rec.image.attached? %>
    <h5 class="card-title">  <%= rec.title %></h5>
    <p class="card-text lead"> <%= rec.body %></p>
  <%= link_to 'show', rec ,class:'btn btn-primary mb-4'%>
  <div class="bg-dark d-block"></div>
  <% end %>
  </div>
</div>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', listing: @recipe %>

<%= link_to 'Back', listings_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>


 
<div class="container d-flex justify-content-center pt-4">
  <div class="card mt-3" style="width: 25rem;">
    

  <%= image_tag(@recipe.image, class:'card-img-top')  %>
    <h5 class="card-title">  <%= @recipe.title %></h5>
    <p class="card-text lead"> This takes <%= @recipe.cooktime %> minutes to cook</p>
      <p class="card-text lead"> <%= @recipe.body %></p>
  </div>
</div>
<%= link_to 'Back', :back,class:'btn btn-secondary btn-sml' %>

<%= render 'recipes/comments' %>

 <% if current_user.is_chef && current_user.chef.recipes.include?(@recipe) %>
      <%= link_to 'Edit', edit_recipe_path(@recipe),class:'btn btn-warning' %> 
    <% end %>