config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # rails admin mounting
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'bookings/index'
 
  resources :recipies
  resources :chefs, except: :index
  resources :listings
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: 'listings#home'

  # allows bookings to have reviews
  resources :bookings do
    resources :reviews
  end
  # allows recipes to have comments
  resources :recipes do
    resources :comments
  end
  resources :payments, only: [:create]  # stripe config
  get'/payments/success', to:'payments#success'
  get'/payments/cancel',to:'payments#cancel'
  post "/payments/webhook", to: "payments#webhook"
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :check_chef_attributes
 
  protected
# ensures users cant access chef only pages
  def authorize_chef
    redirect_to listings_path, notice: 'you must be a chef to access this.' unless current_user.is_chef?
  end
## ensures chefs complete their profile before continuing
  def check_chef_attributes
    if user_signed_in? && current_user.is_chef && !Chef.find_by(user_id: current_user)
      redirect_to new_chef_path, notice: 'Please finalize your chef profile before continuing'
    end
  end
#devise config for allowed params
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name is_chef])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-light sticky-top bg-light">
  <a class="navbar-brand" href="/">ChefSwap</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse  id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item pr-4">
        <%= link_to 'Your bookings', bookings_index_path, class: 'btn btn-outline-dark' %>
      </li>
       <li class="nav-item pr-4">
         <%= link_to 'View listings', listings_path, class: 'btn btn-outline-dark' %>
      </li>
      <% if user_signed_in? && current_user.chef %>
      <li class="nav-item pr-4">
         <%= link_to 'Recipes', recipes_path, class: 'btn btn-outline-dark' %>
      </li>
      
      <% end %>
      
      
      <% if user_signed_in? %>
      <li class="nav-item pr-4">
        <%= link_to 'Edit User profile', edit_user_registration_path, class: 'btn btn-outline-dark' %>
      </li>
      <li class="nav-item pr-4">
      <%= link_to'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-outline-dark ' %> 
      </li>
      <% else %>
      <li class="nav-item pr-4">
      <%= link_to 'Sign-up', new_user_registration_path,class:"btn btn-outline-success" %>
      </li>
      <li class="nav-item pr-4">
      <%= link_to 'Sign-in', new_user_session_path,class:"btn btn-outline-success" %>
      <% end %>
     </ul>
  </div>
</nav>